---
name: Release

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1
        with:
          key: release-rs

      - id: release-detector
        working-directory: release-rs
        env:
          RUST_LOG: debug
        run: |
          # trying to detect a release
          cargo run

          msg=$(git log --oneline -n 1 "${GITHUB_SHA}")
          echo "[INFO] processing: '${msg}'"

          if [[ "${msg}" != *"release"* ]]; then
            echo "[INFO] no release detected"
            echo "::set-output name=release-detected::false"
            exit 0
          fi

          echo "[INFO] release detected"
          pr=$(gh pr list --state merged --search $(git rev-parse HEAD) --limit 1 --json number,url,id,title)
          echo "::set-output name=release-detected::true"

      - uses: Swatinem/rust-cache@v1
        if: ${{ steps.release-detector.outputs.release-detected == 'true' }}
        with:
          key: app

      - if: ${{ steps.release-detector.outputs.release-detected == 'true' }}
        run: cargo build --release
