---
name: Release

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1
        with:
          key: release-rs-01
          working-directory: ./release-rs

      - id: release-detector
        working-directory: release-rs
        env:
          RUST_LOG: debug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # release operator
          cargo run

      - uses: Swatinem/rust-cache@v1
        if: ${{ steps.release-detector.outputs.release-detected == 'true' }}
        with:
          key: app-01

      - if: ${{ steps.release-detector.outputs.release-detected == 'true' }}
        run: |
          # build of release binary
          cargo build --release
